repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: mixed-line-ending
    -   id: pretty-format-json
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        args: [
            --max-complexity, '20',
            --max-line-length, '128',
            --ignore, 'E402'
        ]
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
