FROM docker-registry.mydomain/lab/python:latest
COPY requirements.txt ./
RUN apt-get update && apt-get install -y cron git && \
pip install --no-cache-dir -r requirements.txt && \
rm -rf /var/lib/apt/lists/*
